repos:
  # Fix end of files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=.md
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: check-yaml
      - id: check-json

  # Remove unused imports/variables
  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [
            "--in-place",
            "--remove-all-unused-imports",
            # "--remove-unused-variables",
          ]
  # Flake8
  - repo: https://github.com/pycqa/flake8
    rev: "7.0.0" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        args: [--max-line-length=120]
  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: "5.13.2"
    hooks:
      - id: isort
        args:
          - --profile=black

  # Black formatting
  - repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
      - id: black

  # Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.4
